# Generated by Django 5.2.6 on 2025-10-01 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options_remove_task_is_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('homework', 'Homework'), ('exam', 'Exam'), ('project', 'Project'), ('other', 'Other')], default='not_started', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='todo_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.todolist'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
